version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: ge-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_etablissement
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8001:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql-data:
    driver: local
